### PR TITLE
fix unittest for deepmodeling/dpdispatcher pr #39

### PR DESCRIPTION
**Pull request by felix5572**
fix unittest for deepmodeling/dpdispatcher pr #39

### CODE REVIEW

**Comment by felix5572** [comment]
@y1xiaoc fix unittest.

**Comment by y1xiaoc** [comment]
I didn't think it's a good practice to delete the `.gitignore` and keep tracking of those `out.txt` files in test folder. Those files are suppose to be created every time you run the unit tests and are subject to change in the parallel case (as you correctly mentioned in commit 
3bd9f30). I do not think this is the root of the bug on the github action (see [my comments](https://github.com/deepmodeling/dpdispatcher/pull/39#discussion_r646018473) with Jinzhe). Also, in the cuda test the original assertion is valid since the out.txt in the test dir is *pulled back* from the tmp dir via the parameter `backward_common_files` hence guaranteed to be same as the tmp one. 

However, it seems that removing the git ignore file indeed fix the unit test bug in your github action, which is quite mysterious to me. I will cherry pick the first and last commit and play around with the git ignore file to find the root.

**Comment by felix5572** [comment]
>  `out.txt` in the test dir is pulled back from the tmp dir via the parameter `backward_common_files`

>  emoving the git ignore file indeed fix the unit test bug in your github action,

1. when there is no `out.txt` at `test_if_cuda_multi_devices/test_dir/`, the  `out.txt` is moved (not copied) from `tmp_if_cuda_multi_devices/` to `test_if_cuda_multi_devices/`  

2. when ithere is a `out.txt` in  `test_if_cuda_multi_devices/test_dir/`, the `out.txt` will not be moved

**Comment by y1xiaoc** [comment]
I see. That make sense. I'll see if there's a better solution instead of committing that out.txt every time it changes.

**Comment by felix5572** [comment]
Maybe git ignore the file `test_if_cuda_multi_devices/test_dir/out.txt` and test if the file exits in `test_if_cuda_multi_devices/test_dir/` in unittest

**Comment by y1xiaoc** [comment]
Good idea! Will do in this way.

**Pull request closed without merging**
